### PR TITLE
fix/ removed scrollbar in desktop and solved overflow

### LINKED ISSUE #43: Remove Scrollbar in Pinned Repository Cards for Desktop
For Desktop Remove Scrollbar in Pinned Repository Cards. For Mobile It  should remain the same

image

### PR DESCRIPTION
**Pull request by MacMillon-VS**
@Mridul2820 
I have completed the task.

### Fix:
- Removed Scrollbar in Pinned Repository Cards on Desktop screen. For Mobile, it remains the same.

- If the description is larger than three lines, there is an overflow issue in the cards, which has been fixed.

issue: #43  

Kindly review it, and if there are any changes, please let me know. If everything looks good, kindly accept the request.

Thank you!

### CODE REVIEW

File: components/profile/PinnedRepositories.js [hunk 1]
```diff
@@ -12,7 +12,7 @@ const PinnedRepositories = ({ username, pinnedRepositories }) => {
       <p className="text-center mb-5 text-xl font-semibold">
         {"@"} {username} Pinned Repositories
       </p>
-      <div className="flex flex-wrap justify-center gap-4 max-h-[450px] overflow-y-scroll pt-2 pr-5">
+      <div className="flex flex-wrap justify-center gap-4 max-[805px]:max-h-[450px] min-h-[450px] max-[805px]:overflow-y-scroll pt-2 pr-5">
```
Comment (Mridul2820) [inline components/profile/PinnedRepositories.js:15]: Please use `max-md:` instead of `max-[805px]:`

Comment (MacMillon-VS) [reply components/profile/PinnedRepositories.js:15]: @Mridul2820 When I use max:md if the user has more then 3 pinned repo then it's taking large space. That's not looking good for UX. That's why i used max:[805px] which is break point for 1 card in row to 2 card in a row.
image

**Comment by Mridul2820** [comment]
Thank You For Your contribution
